services:
  - type: web
    name: chinitsuknock
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.11
